### PR TITLE
Add alpha4 ebuilds, update 9999 where required for different installs

### PR DESCRIPTION
**Pull request by fsvm88**

### CODE REVIEW

**Comment by joostruis** [comment]
I can help test this once merged.

**Comment by fsvm88** [comment]
@joostruis All alpha4 packages emerge fine for me, but I still can't test it due to a division-by-zero kernel bug on my RX5700. I'll try to come up with a kernel patch @_@

**Comment by joostruis** [comment]
I have no issues with compilation or running. All seems fine!

**Comment by fsvm88** [comment]
> I have no issues with compilation or running. All seems fine!

Can report the same here -> I finally managed to create kernel patches to make my GPU work =)

If you're interested, this is the issue I opened on FreeDesktop's Gitlab -> https://gitlab.freedesktop.org/drm/amd/-/issues/3729

**Pull request merged**
