### PR TITLE
1.0.0_alpha3: add. resync 9999 ebuilds for installed items. regen metadata

### PR DESCRIPTION
**Pull request by fsvm88**
- add alpha3 ebuilds
- resync 9999 installed files
- refresh metadata

@joostruis can you give it a quick look and see if it seems ok? I couldn't emerge 9999 afterwards due to cosmic-settings pulling in two different versions of the same library and breaking, but alpha3 seems to emerge just fine.

Wwith alpha3 installed and amdgpu (I have a 5700XT), as soon as cosmic-comp starts I get a kernel panic due to a divide error in amdgpu. If you have a different configuration, please test and let me know. I'll search for open bugs on amdgpu in the meantime.

### CODE REVIEW

**Comment by joostruis** [comment]
Yes I can but only after you merged this PR.

**Comment by fsvm88** [comment]
done

**Comment by joostruis** [comment]
Compiled fine. I have not found any unexpected issues except that cosmic-idle was a new package required. 
As we can read in release notes it should be able to launch appimages directly from cosmic files and indeed, that now works. I'm testing this on Intel GPU ( ARC A750 ). I do not have an AMD GPU at hand to test.

Thanks for your work!

**Comment by simonvanderveldt** [comment]
Can also confirm the emerge/compilation went fine (apart from the strange git LFS issues as described in #23).
Starting AppImages from Cosmic Files does indeed work now, which is nice :) Gallery view using space also works :tada: 
And cosmic-panel no longer seems to restart a bunch of times after initial login.

**Pull request merged**
