### PR TITLE
Some minor changes

### PR DESCRIPTION
**Pull request by joostruis**
Hey there! Thanks for your work on this, it seems pretty good so far.

I made some (minimal) changes I required to build it against Gentoo stable tree and package it for MocaccinoOS.

- I made store optional by use flag in the cosmic-meta package
- Removed geoclue as a hard dep. You do not require this at all I believe
- Use stable sci-libs/libqalculate 
- Made cosmic-de/pop-gtk-theme optional by use flag

Please note that once the alpha release gets tagged you require rust 1.79.0 ( see https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/55#issuecomment-2218692444 )

Still not sure about acct-group/cosmic-greeter and acct-user/cosmic-greeter I prefer setting a static UID and a GUI like all other entities in Portage do.

### CODE REVIEW

**Comment by fsvm88** [comment]
Hi, thanks for the interest, glad it's useful to someone :D

1. No problems with the optional package changes, do you think we should/could make them recommended by default? (+IUSE) I'd like to provide a functional-by-default environment for the casual user. Perhaps the store could remain optional.
2. For geoclue, I remember thinking of dropping that myself, however there's an open issue for that at the moment, I recall adding it because of it: https://github.com/pop-os/cosmic-settings-daemon/issues/14
3. Agree on libqalculate (I hoped 5.x would have hit stable by now)
4. I can bump to rust >=1.79 after we merge this PR (which breaks a bit the "stable tree" changes here), thanks for the heads up!
5. I went with auto-determined UID and GID because fixed ones are assigned in tree, and didn't want to risk conflicting with other packages. If this overlay ever gets merged to the main tree, that's a totally valid change that would need to be applied.

**Comment by joostruis** [comment]
1. yes. -store for certain I think.
2. I've been using epoch git for a while on a system where there is no geoclue and neither at compile time and never noticed a problem (or never knew there could be a problem with this to be honest)
3. ok
4. no problemo
5. reasonable thought indeed.

**Comment by fsvm88** [comment]
@joostruis if you want to submit the small changes we discussed above, I can merge this PR and we can move this forward =)

For 2) we can drop it as per your PR, worst case we re-add it later if it breaks anything.

**Comment by joostruis** [comment]
To me it is unclear what small changes I should make. I am uncertain about geoclue. I do believe I had it installed on the system while I was test running. I am 100% sure it isn't required at build time.

**Comment by fsvm88** [comment]
Ah sorry, I went commit-by-commit, and remember seeing the greeter (and perhaps something else) becoming optional and not seeing it removed.

I think it's all fine, actually, sorry for the confusion.

Merging.

**Pull request merged**
